/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "main_gui.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_xfmime_edit (void)
{
  GtkWidget *xfmime_edit;
  GtkWidget *vbox1;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview1;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *hbox3;
  GtkWidget *optionmenu2;
  GtkWidget *hbuttonbox1;
  GtkWidget *save;
  GtkWidget *quit;

  xfmime_edit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (xfmime_edit, 400, 537);
  gtk_window_set_title (GTK_WINDOW (xfmime_edit), "xfmime_edit");
  gtk_window_set_default_size (GTK_WINDOW (xfmime_edit), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (xfmime_edit), vbox1);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 345);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow3, FALSE, TRUE);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow2, TRUE, TRUE);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  optionmenu2 = gtk_option_menu_new ();
  gtk_widget_show (optionmenu2);
  gtk_box_pack_end (GTK_BOX (hbox3), optionmenu2, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox3), hbuttonbox1, FALSE, FALSE, 0);

  save = gtk_button_new_with_mnemonic ("write mime file");
  gtk_widget_show (save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), save);
  GTK_WIDGET_SET_FLAGS (save, GTK_CAN_DEFAULT);

  quit = gtk_button_new_with_mnemonic ("quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), quit);
  GTK_WIDGET_SET_FLAGS (quit, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) treeview1, "drag_data_received",
                    G_CALLBACK (on_drag_data),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "drag_data_get",
                    G_CALLBACK (on_treeview1_drag_data_get),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "drag_drop",
                    G_CALLBACK (on_treeview1_drag_drop),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "drag_motion",
                    G_CALLBACK (on_drag_motion),
                    NULL);
  g_signal_connect ((gpointer) save, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit, "clicked",
                    G_CALLBACK (on_quit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (xfmime_edit, xfmime_edit, "xfmime_edit");
  GLADE_HOOKUP_OBJECT (xfmime_edit, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (xfmime_edit, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (xfmime_edit, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (xfmime_edit, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (xfmime_edit, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (xfmime_edit, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (xfmime_edit, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (xfmime_edit, optionmenu2, "optionmenu2");
  GLADE_HOOKUP_OBJECT (xfmime_edit, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (xfmime_edit, save, "save");
  GLADE_HOOKUP_OBJECT (xfmime_edit, quit, "quit");

  return xfmime_edit;
}

